# Index {.unnumbered}

- adjusted R-squared, 116
- alpha, 31, 37, 189, 191
- American Statistical Association, 203
- analysis of variance, 13, 72, 184
- anova, 17
- ASA Statement on p-Values, 203
- balanced design, 119
- Bonferroni, 193, 198
- categorical response, 141
- chi-squared, 133
- Cochran-Mantel-Haenszel, 133, 150
- Collinearity Diagnostics, 117
- co-primary analyses, 189
- correlated variables, 109
- correlation, 193
- effect size, 35, 37
- factorial designs, 23
- false discovery rate, 202
- Fisher Exact, 133, 149
- fractional factorial designs, 181
- hierarchical testing, 189, 201
- Holm's test, 193, 199
- interaction, 88
- Kruskal-Wallis, 70, 72
- lasso, 118
- logistic regression, 152
- means, 30
- median, 71
- multiple comparison, 195
- multiple hypothesis testing, 195
- multiple regression, 120
- non-normal, 61, 76
- null hypothesis, 195
- ordered categorical variable, 146
- ordered categorical variables, 133, 137
- ordinal logistic regression, 152
- outliers, 61
- paired t-test, 67
- partial least squares, 118
- pilot study, 41
- population, 53
- populations, 49
- power, 18, 29, 191
- principal components regression, 118
- probability, 45, 56, 196
- protocol, 117
- rank, 61
- regression, 13
- Rfit, 70, 90, 93
- ridge regression, 118
- sample size, 13, 32, 37, 45, 51, 67, 191
- simulate, 46
- simulation, 57
- standard deviation, 30, 35, 37, 42, 75, 191
- statistical analysis plan, 117
- tolerance, 117
- t-test, 55
- t-tests, 13
- two-way anova, 87
- type I error, 197
- variability, 19, 21, 30, 42
- variance, 53, 115
- Variance Inflation Factor, 117
- Wilcoxon rank sum, 62
- Wilcoxon signed rank test, 67
